[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/telegram"
  to = "/.netlify/functions/telegram-bot"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
